
#spring:
#  kafka:
#    consumer:
#      bootstrap-servers: localhost:9092
#      group-id: group-id
#      auto-offset-reset: earliest
#      key-deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
#      value-deserializer: "org.springframework.kafka.support.serializer.JsonDeserializer"
#      properties:
#        "[spring.json.value.default.type]": "kube.kafka.monolith.event.model.MessageEvent"
#        "[spring.json.trusted.packages]": "kube.kafka.monolith"
#
#    producer:
#      bootstrap-servers: localhost:9092
#      key-serializer: "org.apache.kafka.common.serialization.StringSerializer"
#      value-serializer: "org.springframework.kafka.support.serializer.JsonSerializer"
#      properties:
#        "[spring.json.add.type.headers]": false

topic:
  payment:
    successful: topic.payment.successful


kafka-bootstap-server: localhost:9092
spring:
  data:
    mongodb:
      uri: mongodb+srv://mongodb:jontesdb@person-webservice.bdj12.mongodb.net/car_rental_db?retryWrites=true&w=majority

