# A key value Secret storage for a Mongo database username and password -NOT USING
apiVersion: v1
kind: Secret
metadata:
    name: mongodb-secret
type: Opaque
data:
    username: dXNlcm5hbWU=
    password: cGFzc3dvcmQ=