# A deployment file for making a pod, out of an external Kafka docker image
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: bitnami/kafka
          ports:
          - containerPort: 9092
          env:
          - name: KAFKA_BROKER_ID
            value: "1"
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: zookeeper-service:2181
          - name: KAFKA_LISTENERS
            value: PLAINTEXT://:9092
          - name: KAFKA_ADVERTISED_LISTENERS
            value: PLAINTEXT://kafka-service:9092
          - name: ALLOW_PLAINTEXT_LISTENER
            value: "yes"
---
# A service for our Kafka Pod and handles the access to it
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  selector:
    app: kafka
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
