apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking
  labels:
    app: booking
spec:
  replicas: 1
  selector:
    matchLabels:
      app:
        booking
  template:
    metadata:
      labels:
        app: booking
    spec:
      containers:
        - name: booking
          image: booking_service:0.0.1-SNAPSHOT
          ports:
          - containerPort: 8082
          env:
          - name: DB_URL
            valueFrom:
              secretKeyRef:
                name: mongo-atlas-secret
                key: db_url
          - name: KAFKA_HOST
            valueFrom:
              configMapKeyRef:
                name: kafka-configmap
                key: kafka_host
#        - name: DB_USERNAME
#          valueFrom:
#            secretKeyRef:
#              name: mongodb-secret
#              key: username
#        - name: DB_PASSWORD
#          valueFrom:
#            secretKeyRef:
#              name: mongodb-secret
#              key: password
---
apiVersion: v1
kind: Service
metadata:
  name: booking-service
spec:
  selector:
    app: booking
#  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
#      nodePort: 30082