apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels:
    app: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app:
        payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: payment_service:0.0.1-SNAPSHOT
          ports:
          - containerPort: 8083
          env:
          - name: KAFKA_HOST
            valueFrom:
              configMapKeyRef:
                name: kafka-configmap
                key: kafka_host
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    app: payment
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
      nodePort: 30083