apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app:
        user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: user_service:0.0.1-SNAPSHOT
          ports:
            - containerPort: 8084
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: mongo-atlas-secret
                  key: db_url
#        - name: DB_USERNAME
#          valueFrom:
#            secretKeyRef:
#              name: mongodb-secret
#              key: username
#        - name: DB_PASSWORD
#          valueFrom:
#            secretKeyRef:
#              name: mongodb-secret
#              key: password
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user
  #  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
#      nodePort: 30082